### ISSUE TITLE
Assurance level too low exception after update from 2.0.9 to 2.1.1 (or 2.2.0) 

### ISSUE THREAD

**Issue by donnyst** [digst/OIOSAML.Java#2]
Recently I tried updating from 2.0.9 to 2.2.0.

However, doing so causes HTTP Status 500 issue:

java.lang.RuntimeException: Assurance level too low: 0, required: 2
	dk.itst.oiosaml.sp.service.SPFilter.doFilter(SPFilter.java:199)
..

This also happens when using 2.1.1.

What was changed from 2.0.9 to 2.1.1 which may cause this?

**Comment by dibgraversen** [comment]
I assume that you are using OIOSAML outside the danish public sector, as an AssuranceLevel claim is issued by the NemLogin IdP.

You can disable the validation of the required AssuranceLevel by setting the required level to 0 in the oiosaml properties file

**Comment by donnyst** [comment]
Ah, okay.

Thanks for the clarification, closing issue.
