### ISSUE TITLE
version in submodules are still 3.0.1-snapshot and parent is 3.0.1

### ISSUE THREAD

**Issue by aparnavodapalli** [digst/OIOSAML.Java#36]
Hi,

oiosaml3-parent is 3.0.1 but the oiosaml3.java is still 3.0.1-snapshot. It needs to have proper versioning.

**Comment by sihpe** [comment]
Hi,

I'm closing this issue. It has been resolved with https://github.com/digst/OIOSAML.Java/pull/37.
