### ISSUE TITLE
migrate to opensaml v3

### ISSUE THREAD

**Issue by nkiesel** [digst/OIOSAML.Java#4]
opensaml v2 is completely unmaintained since 4 years.  Current version is either 3.4.5 or perhaps the just released 4.0.0.

Are there any plans to upgrade?  Given that oiosaml and thus opensaml are used in security-critical places it is really hard to defend why we are using something that depends on unmaintained code.

**Comment by dibgraversen** [comment]
There is currently no plan to update to the OpenSAML 3.x or 4.x series. I suggest posting requests at the project site, which can be located here

https://www.digitaliser.dk/group/42063

**Comment by mdbech** [comment]
With latest release of the reference implementation for Java the OpenSAML 3.4.5 library is used.

Please refer to https://www.digitaliser.dk/news/6072243 for more information.
